### ISSUE TITLE
Update frequency?

### ISSUE THREAD

**Issue by iandoug** [datasets/covid-19#110]
Hi

I'm a new user ... is the data supposed to be updated daily?

Been three days now ...

Thanks, Ian

**Comment by sigmondzavion** [comment]
I count on the data for a weekly report that I run.  
What is the next ETA for an update?

**Comment by sglavoie** [comment]
FIXED: Problem solved in https://github.com/datasets/covid-19/commit/22482c762d6a439b740f8fe8a289f8f76c8455c3 after a manual update.

Hello @iandoug and @sigmondzavion.

It seems like there was a small issue with GitHub Actions which recently started pushing to the branch `main` instead of `master`, a branch that didn't exist. This has been fixed: the default branch is now `main`, being the only minor difference to take into account. Hopefully this is a good enough fix for everyone!
