### ISSUE TITLE
Recovery info missing for 2020-03-24

### ISSUE THREAD

**Issue by karlbateman** [datasets/covid-19#39]
Hey guys, just noticed missing data [here](https://github.com/datasets/covid-19/blob/master/data/worldwide-aggregated.csv#L64).

Incredible work btw :smile:

**Comment by Grelo4ka** [comment]
Yup, the source stopped providing number of people recovered: https://github.com/CSSEGISandData/COVID-19/issues/1250

**Comment by tkubec** [comment]
That's bad. Any idea where to get the data?

**Comment by anuveyatsu** [comment]
@karlbateman @tkubec we're now removing the recovered data since it's being removed in the upstream. It might be updated for some time here https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv but I wouldn't rely on it.

**Comment by anuveyatsu** [comment]
Put back recovery data since it's still available in the upstream.
See https://github.com/datasets/covid-19/commit/09297c4d333059d9826282cef57d135ea29449cc
