### ISSUE TITLE
Datasets are not being updated since 2 days

### ISSUE THREAD

**Issue by deligant** [datasets/covid-19#55]
Hello maintainer,

Data series are not updated since 2 days ago. Is the script updated with the latest chenges in structure from the orignal data sources?

**Comment by ChrisKneller** [comment]
I echo this. I have a dashboard relying on this data. Should I switch to a different source?

**Comment by dennislwy** [comment]
i also upvote this and possible cause is #52

**Comment by nieltg** [comment]
I also have a dashboard [here](https://nieltg.github.io/ncov19-id-analysis) that relies on this data. The CI is running forever [here](https://github.com/datasets/covid-19/actions).

I tried to fix this but I still didn't know is it because the script can't handle the volume of the data or is there something else that makes the script runs forever.

**Comment by anuveyatsu** [comment]
Thanks for reporting - We will fix this asap today.

**Comment by anuveyatsu** [comment]
I've updated the data now. Not closing this issue until next build succeeds.

**Comment by ChrisKneller** [comment]
I see the files on github, but the data at https://datahub.io/core/covid-19 does not seem to be updating with the latest data

**Comment by anuveyatsu** [comment]
FIXED now. See the last build.
