### ISSUE TITLE
Columns instead of Rows for reporting historical data by County, State

### ISSUE THREAD

**Issue by himakarganti** [datasets/covid-19#65]
Can you modify the script to report the cases in columns instead of rows for historical data? It makes it easier to work with for data extraction. Transposing them in Excel or other software is extremely time-consuming for data analytics and this will save a considerable amount of time when working with the dataset with other tools.

**Comment by anuveyatsu** [comment]
@himakarganti can you please give an example of current data and what is expected (desired)? If this is about pivoting the data, we're trying to provide normalized data where possible.

**Comment by himakarganti** [comment]
The current data is reported with the time-series for a place (count, state or country)along a row in the csv file. My request is if they can be reported in columns instead as shown in the Excel file below.
[timedata.xlsx](https://github.com/datasets/covid-19/files/4492859/timedata.xlsx)

**Comment by tungmilan** [comment]
IMO the data format is good because it's in [tidy format](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html). Data aggregation and visualization are much easier with this format. You can always convert from long to wide format using built-in functions ([`pivot_wider()`](https://speakerdeck.com/yutannihilation/a-graphical-introduction-to-tidyrs-pivot-star) in R for example).

**Comment by himakarganti** [comment]
It doesn't help as I need the data in an array for further analysis in Python and I will not be using R or Matlab for it.

**Comment by GerryG07** [comment]
I like the current format. Works fine for my data processing tool.

**Comment by anuveyatsu** [comment]
@himakarganti the main purpose of this project is to provide normalized data with standard metadata (`datapackage.json`). All custom data transformations should be done by users.
