### ISSUE TITLE
use  [try - except] blocks around connection statements

### ISSUE THREAD

**Issue by zomorrod2020** [datasets/covid-19#76]
hello, 
please use [try - except] blocks around codes specially connections. and set execute again if one part raise exception.

**Comment by sglavoie** [comment]
We will improve our current solution as I mentioned in #75. This is indeed very good practice!

However, the connectivity issue is unrelated to the code: we are facing a timeout issue with GitHub Actions because the script takes too long to process. This is an optimization problem only. Still, your suggestion will definitely be applied in our next iteration of the code. :+1:
