### ISSUE TITLE
Updates 7th and 8th July 2020

### ISSUE THREAD

**Issue by robisback** [datasets/covid-19#86]
Will the dataset be updated along these days? Updates seem stuck to 6th July 2020...

**Comment by karansehgal1988** [comment]
Hello, When will we get the latest updates for 7th & 8th July 2020? Please share your inputs....

**Comment by aminoplis** [comment]
Hi, could you please tell me if the automated actions will work again? Thanks in advance.

**Comment by zomorrod2020** [comment]
hi, please update data

**Comment by sglavoie** [comment]
Hello. We are sorry for the inconvenience. This is due to an update on GitHub's side not supporting a slightly older version of Python. The issue should now be fixed as the data was successfully updated a few minutes ago.

Otherwise, please feel free to re-open this issue. Thank you for reporting this!
