### ISSUE TITLE
 Max retries exceeded with url: ...  Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

### ISSUE THREAD

**Issue by zomorrod2020** [datasets/covid-19#87]
hi, this error raised during running code in local pc:

File "/usr/local/lib/python3.7/dist-packages/tabulator/loaders/remote.py", line 71, in load
    raise exceptions.HTTPError(str(exception))
tabulator.exceptions.HTTPError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3263b5de80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by sglavoie** [comment]
We can confirm on our side that the script ran successfully a few minutes ago: https://github.com/datasets/covid-19/actions/runs/163420379

This looks like an temporary outage while you were trying to connect to GitHub. We are using the same sources and script, so this shouldn't be the source of the issue.

Since the script has just finished its execution, you will be able to find the updated data here: https://github.com/datasets/covid-19/tree/master/data

Closing as the newest data is available, the script is running successfully on GitHub Actions and no further immediate action is required.
